general:
  nameOverride: "koo-blog-api"
  namespace: "koo-blog"
serviceAccount:
  create: false
autoscaling:
  enabled: false
deployment:
  replicaCount: 1
  image:
    repository: "122976268003.dkr.ecr.ap-northeast-2.amazonaws.com/koo-blog-api"
    pullPolicy: "IfNotPresent"
    tag: "a088b8b"
  containerPort: 8080
  livenessProbe:
    httpGet:
      path: /hello
      port: 8080
  readinessProbe:
    httpGet:
      path: /hello
      port: 8080
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 1024Mi
service:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:122976268003:certificate/6dbf0a97-5175-4cb5-a52f-8df33809a17e
    alb.ingress.kubernetes.io/healthcheck-path: /hello
    alb.ingress.kubernetes.io/healthcheck-port: '8080'
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
  hosts:
    - host: koo-blog.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
